spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/mymall?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false

